name = "crove-email-inbound-worker"
main = "src/index.ts"
compatibility_date = "2024-11-05"
account_id = "3368ff98a4c956164b7bbdc8fb950163"

[vars]
DESK_WEBHOOK_URL = "https://desk.crove.com/api/third/email/webhook"
DESK_WEBHOOK_SECRET = "crove_email_secret_token_123"
